"""

Revision ID: 3c7c0f7bfbc4
Revises: 04b66376f066
Create Date: 2019-01-18 17:17:11.639233

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3c7c0f7bfbc4'
down_revision = '04b66376f066'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statuses', sa.Column('order_id', sa.Integer(), nullable=False))
    op.drop_constraint(u'statuses_ibfk_1', 'statuses', type_='foreignkey')
    op.drop_constraint(u'statuses_ibfk_2', 'statuses', type_='foreignkey')
    op.create_foreign_key(None, 'statuses', 'orders', ['order_id'], ['id'])
    op.drop_column('statuses', 'source_id')
    op.drop_column('statuses', 'target_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statuses', sa.Column('target_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('statuses', sa.Column('source_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'statuses', type_='foreignkey')
    op.create_foreign_key(u'statuses_ibfk_2', 'statuses', 'user_profile', ['target_id'], ['user_id'])
    op.create_foreign_key(u'statuses_ibfk_1', 'statuses', 'user_profile', ['source_id'], ['user_id'])
    op.drop_column('statuses', 'order_id')
    # ### end Alembic commands ###
