"""empty message

Revision ID: 8898bfa3a2c7
Revises: 3c7c0f7bfbc4
Create Date: 2019-01-19 13:23:21.238856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8898bfa3a2c7'
down_revision = '3c7c0f7bfbc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('status', sa.Enum('SELLING', 'SELLED'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'status')
    # ### end Alembic commands ###
