"""

Revision ID: d8e6f434b20e
Revises: 1848e674bf66
Create Date: 2019-01-18 16:43:24.784378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8e6f434b20e'
down_revision = '1848e674bf66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'user_addresses_ibfk_1', 'user_addresses', type_='foreignkey')
    op.create_foreign_key(None, 'user_addresses', 'user_profile', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_addresses', type_='foreignkey')
    op.create_foreign_key(u'user_addresses_ibfk_1', 'user_addresses', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
