"""

Revision ID: f1fa8bef0a34
Revises: d8e6f434b20e
Create Date: 2019-01-18 16:45:39.372816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1fa8bef0a34'
down_revision = 'd8e6f434b20e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'orders_ibfk_1', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'user_profile', ['buyer_id'], ['user_id'])
    op.drop_constraint(u'products_ibfk_1', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'user_profile', ['seller'], ['user_id'])
    op.drop_constraint(u'statuses_ibfk_1', 'statuses', type_='foreignkey')
    op.drop_constraint(u'statuses_ibfk_2', 'statuses', type_='foreignkey')
    op.create_foreign_key(None, 'statuses', 'user_profile', ['source_id'], ['user_id'])
    op.create_foreign_key(None, 'statuses', 'user_profile', ['target_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'statuses', type_='foreignkey')
    op.drop_constraint(None, 'statuses', type_='foreignkey')
    op.create_foreign_key(u'statuses_ibfk_2', 'statuses', 'user', ['target_id'], ['id'])
    op.create_foreign_key(u'statuses_ibfk_1', 'statuses', 'user', ['source_id'], ['id'])
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(u'products_ibfk_1', 'products', 'user', ['seller'], ['id'])
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(u'orders_ibfk_1', 'orders', 'user', ['buyer_id'], ['id'])
    # ### end Alembic commands ###
